routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;
use TCG\Voyager\Facades\Voyager;

Route::get('/', function () {
    $user = Auth::user();
    return view('welcome', [
        'showComponentsLink' => $user && $user->hasRole(['admin', 'manager'])
    ]);
})->name('welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/lang/{locale}', function ($locale) {
    Session::put('locale', $locale);

    return redirect()->back();
})->name('setLocale');

Route::middleware('auth')->group(function () {
    Route::post('/Component/buy', 'ComponentController@buyComponent')->name('buyComponent');
    Route::post('/Component/add_domain', 'ComponentController@addDomain')->name('addDomain');
    Route::post('/PromoCode/apply', 'PromoCodeController@applyPromoCode')->name('applyPromoCode');
    Route::post('/PromoCode/cancel', 'PromoCodeController@cancelPromoCode')->name('cancelPromoCode');
    Route::get('/Component/delete_domain', 'ComponentController@deleteDomain')->name('deleteDomain');
    Route::get('/Component/download/{component_file}',
        'ComponentController@downloadComponentFile')->name('downloadComponent');
    Route::get('/yandex/cb', 'ComponentController@yandexCb')->name('yandexCb');
    Route::get('/yandex/cb3d', 'ComponentController@yandexCb3d')->name('yandexCb3d');

    Route::middleware('admin')->group(function () {
        Route::get('/regeneration', 'ComponentController@regenerationView')->name('regenerationView');
        Route::get('/regeneration/{user}', 'ComponentController@regenerationUser')->name('regenerationUser');
        Route::get('/regeneration/set_payment/{domain}', 'ComponentController@regenerationSetPayment')->name('regenerationSetPayment');
        Route::get('/regenerate_all', 'ComponentController@regenerateAll')->name('regenerateAll');
        Route::get('/regenerate_component/{component}', 'ComponentController@regenerateComponent')->name('regenerateComponent');
    });

    Route::middleware(['manager'])->group(function () {
        Route::resource('promoCodes', "PromoCodeController");
        Route::resource('payments', "PaymentsController");
    });


});

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});

app/PromoCode.php
<?php

namespace App;

use Eloquent;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Carbon;

/**
 * Class PromoCode
 *
 * @package App
 * @property string $code
 * @property int $type
 * @property int $status
 * @property string $valid_before
 * @property string $component
 * @property string $amount
 * @property int $id
 * @property int $user_id
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read User $user
 * @method static Builder|PromoCode newModelQuery()
 * @method static Builder|PromoCode newQuery()
 * @method static Builder|PromoCode query()
 * @method static Builder|PromoCode whereAmount($value)
 * @method static Builder|PromoCode whereCode($value)
 * @method static Builder|PromoCode whereComponent($value)
 * @method static Builder|PromoCode whereCreatedAt($value)
 * @method static Builder|PromoCode whereId($value)
 * @method static Builder|PromoCode whereStatus($value)
 * @method static Builder|PromoCode whereType($value)
 * @method static Builder|PromoCode whereUpdatedAt($value)
 * @method static Builder|PromoCode whereUserId($value)
 * @method static Builder|PromoCode whereValidBefore($value)
 * @mixin Eloquent
 */
class PromoCode extends Model
{
    const TYPE_DISPOSABLE = 0;
    const TYPE_REUSABLE = 1;
    const STATUS_VALID = 0;
    const STATUS_USED = 1;

    public static function generateUniqCode(): string
    {
        do {
            $code = PromoCode::generateCode();
            $existing = PromoCode::where('code', $code)->first();
        } while ($existing);

        return $code;
    }

    public static function generateCode(): string
    {
        /** @noinspection SpellCheckingInspection */
        $chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        $res = "";
        for ($i = 0; $i < 16; $i++) {
            $res .= $chars[mt_rand(0, strlen($chars) - 1)];
        }
        $parts = str_split($res, 4);
        return implode('-', $parts);
    }

    /**
     * @return User|BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return HasMany
     */
    public function payments(): HasMany
    {
        return $this->hasMany(YandexPayment::class);
    }

    /**
     * @param string $code
     * @return PromoCode|null
     */
    public static function getValid(string $code): ?PromoCode
    {
        return PromoCode::where('code', trim(strtoupper($code)))
            ->where('valid_before', '>', Carbon::now()->toDateTimeString())
            ->where('status', PromoCode::STATUS_VALID)->first();
    }
}

app/Http/Controllers/PromoCodeController.php
<?php

namespace App\Http\Controllers;

use App\PromoCode;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Validation\Rule;

class PromoCodeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        $builder = PromoCode::with([
            'user'
        ])
            ->withCount(['payments' => function (Builder $query) {
                $query->where('status', 'success');
            }])
            ->orderBy('status')
            ->orderBy('created_at', 'desc');
        $promoCodes = $builder->paginate(30);
        return view('promo_codes.index', [
            'promoCodes' => $promoCodes
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Renderable
     */
    public function create(): Renderable
    {
        return view('promo_codes.edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): RedirectResponse
    {
        $maxAmount = config('app.components.mycityselector.maxPromoCodeAmount', 1000);
        $validatedData = $request->validate([
            'valid_before' => 'required|date|after:now',
            'amount'       => "required|integer|between:1,{$maxAmount}",
            'type'         => [
                'required',
                'integer',
                Rule::in([
                    PromoCode::TYPE_DISPOSABLE,
                    PromoCode::TYPE_REUSABLE
                ])
            ]
        ]);
        $promoCode = new PromoCode();
        $promoCode->user()->associate($request->user());
        $promoCode->valid_before = $validatedData['valid_before'];
        $promoCode->component = "mycityselector";
        $promoCode->amount = $validatedData['amount'];
        $promoCode->type = $validatedData['type'];
        $promoCode->code = PromoCode::generateUniqCode();
        $promoCode->save();
        return redirect()->route('promoCodes.index');
    }

//    /**
//     * Display the specified resource.
//     *
//     * @param PromoCode $promoCode
//     * @return Response
//     */
//    public function show(PromoCode $promoCode)
//    {
//        //
//    }
//
//    /**
//     * Show the form for editing the specified resource.
//     *
//     * @param PromoCode $promoCode
//     * @return Response
//     */
//    public function edit(PromoCode $promoCode)
//    {
//        //
//    }
//
//    /**
//     * Update the specified resource in storage.
//     *
//     * @param Request $request
//     * @param PromoCode $promoCode
//     * @return Response
//     */
//    public function update(Request $request, PromoCode $promoCode)
//    {
//        //
//    }

    /**
     * Remove the specified resource from storage.
     *
     * @param PromoCode $promoCode
     * @return RedirectResponse
     * @throws Exception
     */
    public function destroy(PromoCode $promoCode): RedirectResponse
    {
        $promoCode->delete();
        return redirect()->route('promoCodes.index');
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function applyPromoCode(Request $request): RedirectResponse
    {
        $validatedData = $request->validate([
            'promo_code' => 'required|string|max:20',
        ]);
        $promoCode = PromoCode::getValid($validatedData['promo_code']);
        if ($promoCode) {
            Session::put('promo_code', $promoCode->code);
        }
        return redirect()->back();
    }

    public function cancelPromoCode(): RedirectResponse
    {
        Session::remove('promo_code');
        return redirect()->back();
    }

}

resources/views/promo_codes/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <h2>{{__("Promo Code")}}</h2>

                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif
                <form method="post" action="{{route('promoCodes.store')}}">
                    @csrf
                    <div class="form-group">
                        <label for="valid-before-datetime">{{__('Valid before')}}</label>
                        <div>
                            <input class="form-control{{ $errors->has('valid_before') ? ' is-invalid' : '' }}" type="datetime-local" name="valid_before"
                                   value="{{today()->addDays(3)->toDateTimeLocalString()}}" id="valid-before-datetime">
                            @if ($errors->has('valid_before'))
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('valid_before') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="amount">{{__('Amount')}}</label>
                        <input type="text" name="amount"
                               class="form-control {{$errors->has('amount')? 'is-invalid' : ''}}"
                               placeholder="{{__("Enter Promo Code amount in rub")}}"
                               aria-label="{{__("Enter Promo Code amount in rub")}}"
                               value="{{ old('amount') }}">
                        @if ($errors->has('amount'))
                            <div class="invalid-feedback">
                                {{ $errors->first('amount') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="type">{{__('Type')}}</label>
                        <select class="form-control" id="type" name="type">
                            <option value="{{\App\PromoCode::TYPE_REUSABLE}}">{{__('Reusable')}}</option>
                            <option value="{{\App\PromoCode::TYPE_DISPOSABLE}}">{{__('Disposable')}}</option>
                        </select>
                        @if ($errors->has('type'))
                            <div class="invalid-feedback">
                                {{ $errors->first('type') }}
                            </div>
                        @endif
                    </div>
                    <button type="submit" class="btn btn-primary">{{__('Save')}}</button>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/promo_codes/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <h2>{{__("Promo Codes")}}</h2>
                <div class="my-2">
                    <a href="{{route('promoCodes.create')}}">
                        <button type="submit" class="btn btn-primary">{{__('Create')}}</button>
                    </a>
                </div>
                @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                @endif
                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">{{__('Code')}}</th>
                        <th scope="col">{{__('Creator')}}</th>
                        <th scope="col">{{__('Type')}}</th>
                        <th scope="col">{{__('Discount')}}</th>
                        <th scope="col">{{__('Status')}}</th>
                        <th scope="col">{{__('Valid before')}}</th>
                        <th scope="col">{{__('Payments')}}</th>
                        <th scope="col"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($promoCodes as $promoCode)
                        <tr>
                            <td class="align-middle">{{$promoCode->code}}</td>
                            <td class="align-middle">{{$promoCode->user->email}}</td>

                            @switch($promoCode->type)
                                @case(\App\PromoCode::TYPE_DISPOSABLE)
                                <td class="align-middle">{{__('Disposable')}}</td>
                                @break
                                @case(\App\PromoCode::TYPE_REUSABLE)
                                <td class="align-middle">{{__('Reusable')}}</td>
                                @break
                                @default
                                <td class="align-middle">{{__('Unknown')}}</td>
                            @endswitch

                            <td class="align-middle">{{$promoCode->amount}}</td>

                            @if(\Illuminate\Support\Carbon::now()->isAfter($promoCode->valid_before))
                                <td class="align-middle">{{__('Expired')}}</td>
                            @else
                                @switch($promoCode->status)
                                    @case(\App\PromoCode::STATUS_VALID)
                                    <td class="align-middle">{{__('Valid')}}</td>
                                    @break
                                    @case(\App\PromoCode::STATUS_USED)
                                    <td class="align-middle">{{__('Used')}}</td>
                                    @break
                                    @default
                                    <td class="align-middle">{{__('Unknown')}}</td>
                                @endswitch
                            @endif

                            <td class="align-middle">{{$promoCode->valid_before}}</td>
                            <td class="align-middle">
                                @if($promoCode->payments_count > 0)
                                    <a href="{{route('payments.index', ['promo_code_id' => $promoCode->id])}}">({{$promoCode->payments_count}}) {{__('Payments')}}</a>
                                @endif
                            </td>
                            <td class="align-middle">
                                @if($promoCode->status !== \App\PromoCode::STATUS_USED)
                                    <form action="{{route('promoCodes.destroy', ['promoCode' => $promoCode->id])}}"
                                          method="post">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit"
                                                href="{{route('promoCodes.destroy', ['promoCode' => $promoCode->id])}}"
                                                class="btn btn-primary"
                                        >
                                            {{__('Delete')}}
                                        </button>
                                    </form>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{$promoCodes->links()}}
            </div>
        </div>
    </div>
@endsection